name: Tox
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: 3.8
            tox-env: py3
          - python-version: 3.8
            tox-env: flake8
          - python-version: 3.8
            tox-env: black
          - python-version: 3.8
            tox-env: bandit
          - python-version: 3.8
            tox-env: isort
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install virtualenv tox tox-gh-actions wheel
      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: "tox -e ${{ matrix.tox-env }}"
